Presto Gateway/ Expose prometheus metrics
secondmeasure/presto-gateway pull request #1
Opened 2022-02-11 06:36 UTC by cgupte1

1. Exposes prometheus metrics via `/prometheusMetrics` endpoint
2. Adds circleCI config for build and release
3. Adds Docker file for building `presto-gateway` image

2022-02-11 16:58 UTC, bwang-k requested changes
Just an overall question: Is the new Dockerfile/ CircleCI logic intended to replace everything here: https://github.com/secondmeasure/deployments/blob/master/images/presto-gateway/Dockerfile

Current logic is we manually uploaded the presto gateway jar into a "base" image so then that Dockerfile above could use it. If your new changes is intended to replace this flow, I'd recommend creating a parallel PR to remove the presto-gateway folder within images directory so we don't have redundant logic and so this image doesn't get overwritten from two places.

Alternatively, we could have this presto-gateway repo just generate the base image into the presto-gateway/base ECR repo and keep the server logic separate in deployments still. Just a thought.

2022-02-11 22:34 UTC, cgupte1 commented
@bwang-k good point. I have removed the redundant configs from deployments repo as part of https://github.com/secondmeasure/deployments/pull/423/ and updated this PR with docker compose configs.

2022-02-14 16:41 UTC, bwang-k approved these changes

2022-02-14 16:41 UTC, bwang-k commented
LGTM!

2022-02-14 19:47 UTC, merged